version: "3.7"

services:
  web:
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
    build:
      context: .
      target: dev
    ports:
      - 8080:80
    volumes:
      - ./config:/usr/src/config
      - ./public:/usr/src/public
      - ./src:/usr/src/src
